version: "3.8"
services:
  app:
    build:
      context: .
      target: development
      dockerfile: Dockerfile.dev
    image: dm-loganalyzer-dev
    volumes:
      - ./:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    command: npm run dev
